# CMake generated Testfile for 
# Source directory: /home/pi/iota.c/tests
# Build directory: /home/pi/iota.c/examples/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(crypto_crypto "crypto_crypto")
set_tests_properties(crypto_crypto PROPERTIES  _BACKTRACE_TRIPLES "/home/pi/iota.c/tests/CMakeLists.txt;21;add_test;/home/pi/iota.c/tests/CMakeLists.txt;28;add_iota_test;/home/pi/iota.c/tests/CMakeLists.txt;0;")
add_test(core_address "core_address")
set_tests_properties(core_address PROPERTIES  _BACKTRACE_TRIPLES "/home/pi/iota.c/tests/CMakeLists.txt;21;add_test;/home/pi/iota.c/tests/CMakeLists.txt;32;add_iota_test;/home/pi/iota.c/tests/CMakeLists.txt;0;")
add_test(core_inputs "core_inputs")
set_tests_properties(core_inputs PROPERTIES  _BACKTRACE_TRIPLES "/home/pi/iota.c/tests/CMakeLists.txt;21;add_test;/home/pi/iota.c/tests/CMakeLists.txt;33;add_iota_test;/home/pi/iota.c/tests/CMakeLists.txt;0;")
add_test(core_outputs "core_outputs")
set_tests_properties(core_outputs PROPERTIES  _BACKTRACE_TRIPLES "/home/pi/iota.c/tests/CMakeLists.txt;21;add_test;/home/pi/iota.c/tests/CMakeLists.txt;34;add_iota_test;/home/pi/iota.c/tests/CMakeLists.txt;0;")
add_test(core_iota_str "core_iota_str")
set_tests_properties(core_iota_str PROPERTIES  _BACKTRACE_TRIPLES "/home/pi/iota.c/tests/CMakeLists.txt;21;add_test;/home/pi/iota.c/tests/CMakeLists.txt;35;add_iota_test;/home/pi/iota.c/tests/CMakeLists.txt;0;")
add_test(core_byte_buffer "core_byte_buffer")
set_tests_properties(core_byte_buffer PROPERTIES  _BACKTRACE_TRIPLES "/home/pi/iota.c/tests/CMakeLists.txt;21;add_test;/home/pi/iota.c/tests/CMakeLists.txt;39;add_iota_test;/home/pi/iota.c/tests/CMakeLists.txt;0;")
add_test(core_slip10 "core_slip10")
set_tests_properties(core_slip10 PROPERTIES  _BACKTRACE_TRIPLES "/home/pi/iota.c/tests/CMakeLists.txt;21;add_test;/home/pi/iota.c/tests/CMakeLists.txt;40;add_iota_test;/home/pi/iota.c/tests/CMakeLists.txt;0;")
add_test(core_utils_bech32 "core_utils_bech32")
set_tests_properties(core_utils_bech32 PROPERTIES  _BACKTRACE_TRIPLES "/home/pi/iota.c/tests/CMakeLists.txt;21;add_test;/home/pi/iota.c/tests/CMakeLists.txt;41;add_iota_test;/home/pi/iota.c/tests/CMakeLists.txt;0;")
add_test(core_transaction "core_transaction")
set_tests_properties(core_transaction PROPERTIES  _BACKTRACE_TRIPLES "/home/pi/iota.c/tests/CMakeLists.txt;21;add_test;/home/pi/iota.c/tests/CMakeLists.txt;42;add_iota_test;/home/pi/iota.c/tests/CMakeLists.txt;0;")
add_test(core_indexation "core_indexation")
set_tests_properties(core_indexation PROPERTIES  _BACKTRACE_TRIPLES "/home/pi/iota.c/tests/CMakeLists.txt;21;add_test;/home/pi/iota.c/tests/CMakeLists.txt;43;add_iota_test;/home/pi/iota.c/tests/CMakeLists.txt;0;")
add_test(core_message "core_message")
set_tests_properties(core_message PROPERTIES  _BACKTRACE_TRIPLES "/home/pi/iota.c/tests/CMakeLists.txt;21;add_test;/home/pi/iota.c/tests/CMakeLists.txt;44;add_iota_test;/home/pi/iota.c/tests/CMakeLists.txt;0;")
add_test(client_http "client_http")
set_tests_properties(client_http PROPERTIES  _BACKTRACE_TRIPLES "/home/pi/iota.c/tests/CMakeLists.txt;21;add_test;/home/pi/iota.c/tests/CMakeLists.txt;47;add_iota_test;/home/pi/iota.c/tests/CMakeLists.txt;0;")
add_test(client_json "client_json")
set_tests_properties(client_json PROPERTIES  _BACKTRACE_TRIPLES "/home/pi/iota.c/tests/CMakeLists.txt;21;add_test;/home/pi/iota.c/tests/CMakeLists.txt;48;add_iota_test;/home/pi/iota.c/tests/CMakeLists.txt;0;")
add_test(client_message_builder "client_message_builder")
set_tests_properties(client_message_builder PROPERTIES  _BACKTRACE_TRIPLES "/home/pi/iota.c/tests/CMakeLists.txt;21;add_test;/home/pi/iota.c/tests/CMakeLists.txt;49;add_iota_test;/home/pi/iota.c/tests/CMakeLists.txt;0;")
add_test(client_get_info "client_get_info")
set_tests_properties(client_get_info PROPERTIES  _BACKTRACE_TRIPLES "/home/pi/iota.c/tests/CMakeLists.txt;21;add_test;/home/pi/iota.c/tests/CMakeLists.txt;50;add_iota_test;/home/pi/iota.c/tests/CMakeLists.txt;0;")
add_test(client_get_balance "client_get_balance")
set_tests_properties(client_get_balance PROPERTIES  _BACKTRACE_TRIPLES "/home/pi/iota.c/tests/CMakeLists.txt;21;add_test;/home/pi/iota.c/tests/CMakeLists.txt;51;add_iota_test;/home/pi/iota.c/tests/CMakeLists.txt;0;")
add_test(client_res_error "client_res_error")
set_tests_properties(client_res_error PROPERTIES  _BACKTRACE_TRIPLES "/home/pi/iota.c/tests/CMakeLists.txt;21;add_test;/home/pi/iota.c/tests/CMakeLists.txt;52;add_iota_test;/home/pi/iota.c/tests/CMakeLists.txt;0;")
add_test(client_get_tips "client_get_tips")
set_tests_properties(client_get_tips PROPERTIES  _BACKTRACE_TRIPLES "/home/pi/iota.c/tests/CMakeLists.txt;21;add_test;/home/pi/iota.c/tests/CMakeLists.txt;53;add_iota_test;/home/pi/iota.c/tests/CMakeLists.txt;0;")
add_test(client_output_from_addr "client_output_from_addr")
set_tests_properties(client_output_from_addr PROPERTIES  _BACKTRACE_TRIPLES "/home/pi/iota.c/tests/CMakeLists.txt;21;add_test;/home/pi/iota.c/tests/CMakeLists.txt;54;add_iota_test;/home/pi/iota.c/tests/CMakeLists.txt;0;")
add_test(client_get_output "client_get_output")
set_tests_properties(client_get_output PROPERTIES  _BACKTRACE_TRIPLES "/home/pi/iota.c/tests/CMakeLists.txt;21;add_test;/home/pi/iota.c/tests/CMakeLists.txt;55;add_iota_test;/home/pi/iota.c/tests/CMakeLists.txt;0;")
add_test(client_get_health "client_get_health")
set_tests_properties(client_get_health PROPERTIES  _BACKTRACE_TRIPLES "/home/pi/iota.c/tests/CMakeLists.txt;21;add_test;/home/pi/iota.c/tests/CMakeLists.txt;56;add_iota_test;/home/pi/iota.c/tests/CMakeLists.txt;0;")
add_test(client_get_message "client_get_message")
set_tests_properties(client_get_message PROPERTIES  _BACKTRACE_TRIPLES "/home/pi/iota.c/tests/CMakeLists.txt;21;add_test;/home/pi/iota.c/tests/CMakeLists.txt;57;add_iota_test;/home/pi/iota.c/tests/CMakeLists.txt;0;")
add_test(client_send_message "client_send_message")
set_tests_properties(client_send_message PROPERTIES  _BACKTRACE_TRIPLES "/home/pi/iota.c/tests/CMakeLists.txt;21;add_test;/home/pi/iota.c/tests/CMakeLists.txt;58;add_iota_test;/home/pi/iota.c/tests/CMakeLists.txt;0;")
add_test(client_find_message "client_find_message")
set_tests_properties(client_find_message PROPERTIES  _BACKTRACE_TRIPLES "/home/pi/iota.c/tests/CMakeLists.txt;21;add_test;/home/pi/iota.c/tests/CMakeLists.txt;59;add_iota_test;/home/pi/iota.c/tests/CMakeLists.txt;0;")
add_test(client_message_meta "client_message_meta")
set_tests_properties(client_message_meta PROPERTIES  _BACKTRACE_TRIPLES "/home/pi/iota.c/tests/CMakeLists.txt;21;add_test;/home/pi/iota.c/tests/CMakeLists.txt;60;add_iota_test;/home/pi/iota.c/tests/CMakeLists.txt;0;")
add_test(client_message_children "client_message_children")
set_tests_properties(client_message_children PROPERTIES  _BACKTRACE_TRIPLES "/home/pi/iota.c/tests/CMakeLists.txt;21;add_test;/home/pi/iota.c/tests/CMakeLists.txt;61;add_iota_test;/home/pi/iota.c/tests/CMakeLists.txt;0;")
add_test(test_wallet_api "test_wallet_api")
set_tests_properties(test_wallet_api PROPERTIES  _BACKTRACE_TRIPLES "/home/pi/iota.c/tests/CMakeLists.txt;68;add_test;/home/pi/iota.c/tests/CMakeLists.txt;0;")
